// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX4cLB4Llrbk9JDGnRkwAeSYYGGhit_u8',
    appId: '1:208020628865:web:9b460ced0ce8920818b480',
    messagingSenderId: '208020628865',
    projectId: 'bloodconnect-9d457',
    authDomain: 'bloodconnect-9d457.firebaseapp.com',
    storageBucket: 'bloodconnect-9d457.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCupiBixK8RDSIsTjX33Hx7vYWihVGaSQk',
    appId: '1:208020628865:android:e03ecfabb12991f918b480',
    messagingSenderId: '208020628865',
    projectId: 'bloodconnect-9d457',
    storageBucket: 'bloodconnect-9d457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFBRGCW9c48SCyzhUEg72k8SOta6wgAaw',
    appId: '1:208020628865:ios:e11611fd1261888818b480',
    messagingSenderId: '208020628865',
    projectId: 'bloodconnect-9d457',
    storageBucket: 'bloodconnect-9d457.firebasestorage.app',
    iosBundleId: 'com.example.bloodConnect',
  );
}
